select B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
from (select FOOD_TYPE, MAX(FAVORITES) FAVORITES
      from REST_INFO
      group by FOOD_TYPE) A, REST_INFO B
where A.FOOD_TYPE = B.FOOD_TYPE and A.FAVORITES = B.FAVORITES
order by FOOD_TYPE desc;