SELECT
    MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM
    MEMBER_PROFILE
WHERE
    TLNO is not NULL                    AND
    TO_CHAR(DATE_OF_BIRTH, 'MM') = 3    AND
    GENDER = 'W'
    order by MEMBER_ID